#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Sensor, S4,     gyroRobot,      sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armRight,      tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     armLeft,       tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void moveArm(int pwr, int msec)
    {
        float majorMsec = msec * 0.05;
        float minorMsec = msec * 0.95;

        float newPwr = 0.0;
        float newMsec = 0.0;

        motor[armLeft] = pwr;
        motor[armRight] = pwr;

        wait1Msec(majorMsec);

        while(newMsec <= minorMsec)
        {
        		nxtDisplayString(3, "%d", newPwr);
						nxtDisplayString(4, "%d", newMsec);
            newPwr = -(pwr/minorMsec)*newMsec + pwr;
            motor[armLeft] = newPwr;
            motor[armRight] = newPwr;
            wait1Msec(1);
            newMsec += 1.0;
        }
        motor[armLeft] = 0;
        motor[armRight] = 0;
        /*for(int count = 0; count <= 10; count++)
        {
            ratioChange = count/10.0;
            pwrRatio -= ratioChange;
            msecRatio += ratioChange;
            newPwr = pwr*pwrRatio;
            newMsec = minorMsec*msecRatio;
            motor[armLeft] = newPwr;
            motor[armLeft] = newPwr;
            wait1Msec(newMsec);
        }

        motor[armLeft] = 0;
        motor[armRight] = 0;*/
    }
task main()
{
motor[armLeft] = 10;
	motor[armRight] = 10;

	wait10Msec(25);

	motor[armLeft] = 0;
	motor[armRight] = 0;

	while(SensorValue[touchSensor] == false)
	{
		motor[armLeft] = -7;
		motor[armRight] = -7;
	}
	wait1Msec(100);
	motor[armLeft] = 0;
	motor[armRight] = 0;

	nMotorEncoder[driveLeft] = 0;
	nMotorEncoder[driveRight] = 0;
	nMotorEncoder[armLeft] = 0;
	//HTGYROstartCal(3);
	ClearTimer(T1);
	ClearTimer(T2);

	PlayTone(440, 30);
	wait10Msec(50);

moveArm(5, 800);
PlayTone(440,200);
}
