#pragma config(Sensor, S1,     ,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void earthquake()
{
  //What would display?
  double richterScale = 2.0;

  if(richterScale < 100.0)
  {
    nxtDisplayString(3,"%s", "tah'ts a rlealy rtosgn erqutakahe!");
  }
  if(richterScale < 5.0)
  {
    nxtDisplayString(3,"%s", "Whoa, that building fell down!");
  }
  if(richterScale < 2.0)
  {
    nxtDisplayString(3,"%s", "There was an earthquake, right?");
  }
  if(richterScale < 1.0)
  {
    nxtDisplayString(3,"%s", "wiggle wiggle");
  }
}


void mystery()
{
  //What would be displayed, if light sensor read 60?
  int lightSensor = SensorValue[S1];

  while(true)
  {
    if(lightSensor = 0)
    {
      nxtDisplayString(3,"%s", "I can't see anything!!!";
    }
    else
    {
      nxtDisplayString(3,"%s", "I see the light");
    }

    wait1Msec(50);
    lightSensor = sensorValue[S1];
  }
}


void fun()
{
  //What would the string result be equal to?
    string object = "wind";
    string status = "high";
    string result = "";

    if(object == "world")
    {
      if(status == "round");
      {
        result = "it turns me on"
      }
    }
    else if(object == "wind")
    {
      if(status == "high");
      {
        result = "it blows my mind"
      }
    }
    else if(object == "sky")
    {
      if(status == "blue");
      {
        result = "it makes me cry"
      }
    }
    else
    {
      result = "aaaaahhhhhhhhhhhh"
    }
}


void cool()
{
  //Would this run correctly?
  while(true){motor[motorA]=50;motor[motorB]=50;motor[motorC]=75;string str="hellotherepeoples";int x=9/3*2+13/9-1;wait1Msec(50);}
}
