/*Program for moving forward until a touch sensor is pressed*/
#pragma config(Sensor, S1,     ,               sensorSONAR)
#pragma config(Sensor, S2,     ,               sensorTouch)
#pragma config(Sensor, S3,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*Initiate sensors and define ports*/
task main()
{
  do  //runs motors forward until the touch sensor is pressed
  {
   motor[motorA]=30;
   motor[motorC]=30;
  }while(SensorValue[sensorTouch]==0)  //stops motors after touch sensor is pressed
  {
    motor[motorA]=0;
    motor[motorC]=0;
  }
}
