#pragma config(StandardModel, "Virtual Worlds NXT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  nMotorEncoder[motorB] = 0;
  nMotorEncoder[motorC] = 0;

  nMotorEncoderTarget[motorB] = 1800;
  nMotorEncoderTarget[motorC] = 1800;

  motor[motorC] = 50;
  motor[motorB] = 50;

  while(nMotorRunState[motorB] != runStateIdle || nMotorRunState[motorC] != runStateIdle)
  {

  }
}
