#pragma config(Sensor, S1,     HTMC,           sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-compass.h"
#include "hitechnic-sensormux.h"

task main()
{
	//HTMCstartCal(HTMC);
	//wait1Msec(5000);
	//PlayTone(440,30);
	//HTMCstopCal(HTMC);
	while(true)
	{
		nxtDisplayString(3 ,"sensy: %d", HTMCreadHeading(HTMC));
	}
}
