#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task Intake()
{
	string object = "";
	int numBlock = 0;
	bool isBlock = false;

	while(numBlock <= 4)
	{
		if(SensorValue[lightSensor] > 40)
		{
			wait1Msec(250);
			if(SensorValue[lightSensor] >= 43)
			{
				PlayTone(440,1);
				object = "block ";
				isBlock = true;
			}
			else
			{
				PlayTone(300,1);
				object = "paddle";
			}
		}
		else
		{
			object = "      ";
			if(isBlock)
			{
				numBlock++;
				isBlock = false;
			}
		}

		nxtDisplayString(3,"%s",object);
		nxtDisplayString(4,"numBlock: %d", numBlock);
		nxtDisplayString(5,"%d",SensorValue[lightSensor]);
	}
}

task main()
{
	StartTask(Intake);
}
