#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     robotMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    robotServo,           tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	while(true)
	{
		float servoVal1 = ((256.0/180.0) * atan(joystick.joy1_y1 / joystick.joy1_x1));								//
		float servoVal2 = ((256.0/180.0) * (180.0 - abs(atan(joystick.joy1_y1 / joystick.joy1_x1))));		//
		float servoVal3 = 256.0/2.0;
		writeDebugStreamLine(" servoVal1 = %d", servoVal1);
		getJoystickSettings(joystick);
		nxtDisplayString( 1, "%d", servoVal1);
		wait10Msec(1000);
		if(abs(joystick.joy1_y1) > 15)
		{
			motor[robotMotor] = joystick.joy1_y1;
		}
		if(joystick.joy1_x2 > 0)
		{
			servo[robotServo] = servoVal1;
		}
		else if(joystick.joy1_x2 < 0)
		{
			servo[robotServo] = servoVal2;
		}
		else if(joystick.joy1_x2 == 0)
		{
			servo[robotServo] = servoVal3;
		}
	}
}
