#pragma config(Sensor, S1,     light,          sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main
{
	while(true)
	{
	nxtDisplayCenteredTextLine(2,"%d",SensorValue[light]);
}
}
