#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void cosineRamp(int time , float maxPwr, float initPwr)
{
	float period = time * 0.001 * 0.5 * PI;
	ClearTimer(T1);
	while(time100[T1] <= time)
	{
		float power = -maxPwr * cos(period * time100[T1] * 0.001) + maxPwr + initPwr;
		motor[leftDrive] = power;
		motor[rightDrive] = power;
	}
}

task main()
{
	cosineRamp(20 , 30.0, 30.0);
}
