#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          ttMot,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-gyro.h"
task main()
{
	HTGYROstartCal(gyro);
	nMotorEncoder[ttMot] = 0;
	nMotorEncoderTarget[ttMot] = 0;
	motor[ttMot] = 100;
	//ClearTimer(T1);
	while(nMotorEncoder[ttMot] <360)//> -360)
	{
		writeDebugStreamLine("%f",SensorValue[gyro]);
		//writeDebugStreamLine("%f",(time1[T1]/1000.0)/2.0);
	}
	motor[ttMot] = 0;
	writeDebugStreamLine("FINAL: %f", SensorValue[gyro]);
	//writeDebugStreamLine("FINAL: %f",(time1[T1]/1000.0)/2.0);


}
