#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    elServo,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{/*
	servo[elServo] = 255;
	wait1Msec(20000);
	*/
/*
	servo[elServo] = 223;
	wait1Msec(7000);
	*/
	/*
	servo[elServo] = 192;
	wait1Msec(5000);*/

	servo[elServo] = 7;
	wait1Msec(20000);

	/*for(int count = 255; count > 200; count -= 5)
	{
		servo[elServo] = count;
		wait1Msec(2250);
	}*/
}
