#pragma config(Sensor, S1,     SMUXERS,        sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"
#include "lego-sound.h"
#include "hitechnic-accelerometer.h"
#include "hitechnic-gyro.h"

const tMUXSensor USSR = msensor_S1_4;
const tMUXSensor gyro = msensor_S1_3;
const tMUXSensor accel = msensor_S1_2;
const tMUXSensor mic = msensor_S1_1;
task main()
{
	int USval = 0;
	int micVal = 0;
	int accelVal = 0;
	int gyroVal = 0;
int x = 0;
int y = 0;
int z = 0;
	while(true)
	{
		USval = USreadDist(USSR);
		micVal = SNDreadRaw(mic);
		accelVal = HTACreadAllAxes(accel, x, y, z);
		gyroVal = HTGYROreadRot(gyro);

		nxtDisplayString(1,"USSR: %d", USval);
		nxtDisplayString(2,"mic: %d", micVal);
		nxtDisplayString(3,"gyro: %d", gyroVal);
		nxtDisplayString(4,"accel: %d", accelVal);
	}

}
