#pragma config(Motor,  motorA,          ttMot,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

const float JOY2ANG = 360.0/128.0;
bool isMoving = false;

/*task MoveMotor()
{
while(true)
{
while(nMotorRunState[ttMot] != runStateIdle)
{
PlayTone(440,30);
}
motor[ttMot] = 0;
isMoving = false;
}
}*/

task main()
{
	bFloatDuringInactiveMotorPWM = false;
	float inputAng = 0.0;
	nMotorEncoder[ttMot] = 0;
	nMotorEncoderTarget[ttMot] = 0;
	bool posMove = false;
	int currHeading = 0;
	float angDiff = 0.0;
	float motPow = 0.0;
	//StartTask(MoveMotor);
	waitForStart();

	while(true)
	{
		getJoystickSettings(joystick);
		if(abs(joystick.joy1_x1) > 10)
		{
			if(!isMoving)
			{
				inputAng = joystick.joy1_x1*JOY2ANG;
				if(joystick.joy1_x1 > 0)
				{
					motor[ttMot] = 100;
					posMove = true;
				}
				else
				{
					motor[ttMot] = -100;
					posMove = false;
				}

				nMotorEncoderTarget[ttMot] = inputAng;
				isMoving = true;
				writeDebugStreamLine("inputAng: %f", inputAng);
			}

			else
			{
				//angDiff = nMotorEncoderTarget[ttMot] - nMotorEncoder[ttMot];
				//(360,100) (0,0)
				motPow = 100.0 + (100.0/360.0)*(joystick.joy1_x1*JOY2ANG-360.0);
				motor[ttMot] = motPow;


				if(posMove)
				{
					while(nMotorEncoder[ttMot] < nMotorEncoderTarget[ttMot])
					{
						writeDebugStreamLine("encoder: %f", nMotorEncoder[ttMot]);
						writeDebugStreamLine("target: %f", nMotorEncoderTarget[ttMot]);
					}
				}
				else
				{
					while(nMotorEncoder[ttMot] > nMotorEncoderTarget[ttMot])
					{
						writeDebugStreamLine("encoder: %f", nMotorEncoder[ttMot]);
						writeDebugStreamLine("target: %f", nMotorEncoderTarget[ttMot]);
					}
				}

				motor[ttMot] = 0;
				PlayTone(440,1);
			}
		}
		else
		{
			nMotorEncoder[ttMot] = 0;
			nMotorEncoderTarget[ttMot] = 0;
			motor[ttMot] = 0;
			isMoving = false;
		}
	}
}
