#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     SMUXER,         sensorI2CCustom9V)
#pragma config(Motor,  motorA,          sweFR,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     sweBR,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     sweBL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     sweFR,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     sweFL,         tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    swiFR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    swiFL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    swiBR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    swiBL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-sensormux.h"
#include "hitechnic-gyro.h"
const tMUXSensor gyroTT = msensor_S2_2;
const tMUXSensor gyroRobot = msensor_S2_1;
const float PINC_SCALE = 0.78125; //100.0/128.0; convert joy val to pwr
const float ANG2SERVO = 15.25/180.0;//for giant servos, but 256.0/180.0; for standard
const float SERVO2TIME = 2.0; //20.0/10.0; convert servo val to Msec
const float POS_PIV = 45.0*ANG2SERVO;
const float NEG_PIV = 135.0*ANG2SERVO;

#include "arps_functions2.h"

//same concept as drive train rotation

//if negative x, turn CCW
//if positive x, turn CW
//power is always 100
//power increment is proportional to |x|
//need gyro limit: account for gyroRobot addition.


float getTTAngChange()
{

}

task main()
{
	waitForStart();

	while(true)
	{
		getJoystickSettings(joystick);
		float motPow = joystick.joy1_x2*PINC_SCALE;

		if(abs(joystick.joy1_x2) > 10)
		{


		}
		else
		{

		}
	}
}
