#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     US,             sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     L,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     R,             tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int count = 0;

task DisplayUS()
{
		while(true)
	{
		nxtDisplayString(1, "US: %d", SensorValue[US]);
		nxtDisplayString(2, "WffCnt: %d", count);
		wait10Msec(10);
		eraseDisplay();
	}
}

task SoundPlay()
{
}

task Count()
{
	while(true)
	{ bool block = false;
		if(SensorValue(US) < 9)
		{
			count += 1;
		}
		else
		{
			count = count;
		}
	}
}

task main()
{
	StartTask(DisplayUS);
	StartTask(SoundPlay);
	StartTask(Count);
	motor[L] = 50;
	motor[R] = 50;
	wait10Msec(1000);
	motor[L] = 0;
	motor[R] = 0;
}
