#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     SMUX,           sensorI2CCustom)
#pragma config(Sensor, S3,     TUX,            sensorHiTechnicTouchMux)
#pragma config(Sensor, S4,     gyroRobot,      sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          flagLeft,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          flagRight,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armRight,      tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     armLeft,       tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/***********************************
** WHS Robotics  |  FTC Team 542  **
** Ring It Up! 2012-2013 Season   **
** Autonomous Series 2            **
** Defensive blocking							**
** Main  |  Blue or Red  |  V1    **
***********************************/


///////////////////////////INCLUDES////////////////////////////
#include "JoystickDriver.c"  //file to "handle" the Bluetooth messages.
#include "autonomous_constants_globVars.h"  //header file with autonomous KONSTANTS and global variables
#include "autonomous_functions1.h"  //header file with autonomous functions
#include "autonomous_tasks1.h"  //header file with autonomous tasks



////////////////////////INITIALIZATION/////////////////////////
void initializeRobot()
{
  resetArm();

	//reset drive train encoders
	nMotorEncoder[driveLeft] = 0;
	nMotorEncoder[driveRight] = 0;

	HTGYROstartCal(gyroRobot); //calibrate gyro

	//clear timers T1 and T2
	ClearTimer(T1);
	ClearTimer(T2);

	resetFlags();

	//beep (because it's Windsor)
	PlayTone(440, 30);

  return;
}

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	moveStraight(51,50);
}
