#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Sensor, S4,     gyroRobot,      sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armRight,      tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     armLeft,       tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "autonomous_functions1.h"  //Include header file with the autonomous functions
#include "autonomous_constants_globVars.h"  //Include header file with the autonomous KONSTANTS and global variables




/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	motor[armLeft] = 10;
	motor[armRight] = 10;

	wait10Msec(25);

	motor[armLeft] = 0;
	motor[armRight] = 0;

	while(SensorValue[touchSensor] == false)
	{
		motor[armLeft] = -7;
		motor[armRight] = -7;
	}
	wait1Msec(100);
	motor[armLeft] = 0;
	motor[armRight] = 0;

	nMotorEncoder[driveLeft] = 0;
	nMotorEncoder[driveRight] = 0;
	nMotorEncoder[armLeft] = 0;
	HTGYROstartCal(3);
	ClearTimer(T1);
	ClearTimer(T2);

	PlayTone(440, 30);
	//Move arm down until touch sensor is pressed (Port 4 on multiplexer; multiplexer is port 2)
	//reset encoders on drive train and arm
	//beep
  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  //raise arm to IR beacon level
	moveArm(3, 1250);

	//move to plywood
  moveStraight(28,50);

  if(SensorValue[IRSensor] != -1)
	{
		if(SensorValue[IRSensor] >= 6)
		{
			//IR beacon is on the right
			PlayTone(500, 100);
			//back up about one floor tile (24 inches)
			wait10Msec(50);
			moveStraight(19, -25);
			//turn 45 degrees to line up with beacon
			gyroCenterPivot(45, 20);
			//move straight to the right peg and score (raise arm to make sure it is at the hardstop)
			moveStraight(31, 20);
			moveArm(20, 1000);
			moveStraight(10, 50);
			//lower the arm a bit to back away
			moveArm(-7, 600);
			moveStraight(6, -15);
			moveArm(-8, 600);
			//back up
			moveStraight(12, -15);
			gyroCenterPivot(-140, 50);
			moveStraight(30, 50);
			gyroCenterPivot(80, 50);
			moveStraight(40, 50);

		}
		else if(SensorValue[IRSensor] <= 4)
		{
			//IR beacon is on the left
			PlayTone(380, 100);
			//move forward more than middle
			//moveStraight(4,25);
			gyroCenterPivot(-30, 15);
			moveStraight(29,15);
			gyroCenterPivot(94, 5);
			//turn about the same amt
			///SCORING
			moveStraight(16, 15);
			moveArm(8,1000);
			moveStraight(13, 13);
			//move forward to goal
			//lower arm 1/8 tsp
			//move backwards
			moveArm(-7, 400);
			moveStraight(3, -10);
			moveArm(-8, 430);
			moveStraight(15, -10);
			//move to dispenser
			gyroCenterPivot(-100, 50);
			moveStraight(15, 50);
		}
		else if(SensorValue[IRSensor] == 5)
		{
			//IR beacon is in the middle
			PlayTone(440, 100);
			moveStraight(9, 50);
			gyroCenterPivot(54, 10);
			///SCORING
			//raise the arm
			moveStraight(13, 15);
			moveArm(9, 600);
			moveStraight(7, 15);
			//lower arm 1/8 tsp
			//move backwards
			moveArm(-7, 400);
			moveStraight(3, -10);
			moveArm(-7, 300);
			moveStraight(12, -10);
			//drive to dispenser CHANGE!!!!
			gyroCenterPivot(-95, 50);
			moveStraight(30, 50);
		}
	}

  while (true)
  {
  	//move forward
  	//take an IR reading
  	//move accordingly! =D
  }
}
