#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armLeft,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     armRight,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    clawRightX,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    clawLeftX,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    clawRightY,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    clawLeftY,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//INSERT PRAGMAS

/*************************************
** This is version 1 of teleop main **
** for WHS Robotics FTC Team 542,   **
** for Ring It Up ('12-'13).        **
**************************************/

//-----------------------Includes-------------------------
#include "teleop_tasks1.h";


/*********************************
** initializeRobot initializes  **
** servos to starting positions **
** and finds error for sensors. **
**********************************/
void initializeRobot()
{
	claw_reset();
  return;
}


//-------------------------main---------------------------
task main()
{
  initializeRobot();

  waitForStart();

  //start tasks
  StartTask(RunTankDrive);
  //StartTask(RunArm);
  StartTask(RunClaw);

  while(true) //teleop phase
  {
    getJoystickSettings(joystick);

    //Sensor-related thing joy1Btn(1)
    //Sensor-related thing joy1Btn(2)
    //Sensor-related thing joy1Brn(3)

  }
}
