#pragma config(Hubs, S1, HTMotor, HTMotor, HTMotor, HTServo)
#pragma config(Sensor, S1, , sensorI2CMuxController)
#pragma config(Sensor, S2, touchSensor, sensorTouch)
#pragma config(Sensor, S3, IRSensor, sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4, gyroSensor, sensorI2CHiTechnicGyro)
#pragma config(Motor, motorA, rightIntake, tmotorNXT, PIDControl, encoder)
#pragma config(Motor, motorB, leftIntake, tmotorNXT, PIDControl, encoder)
#pragma config(Motor, motorC, , tmotorNXT, openLoop)
#pragma config(Motor, mtr_S1_C1_1, leftDrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor, mtr_S1_C1_2, rightDrive, tmotorTetrix, PIDControl)
#pragma config(Motor, mtr_S1_C2_1, leftArm, tmotorTetrix, openLoop, reversed)
#pragma config(Motor, mtr_S1_C2_2, rightArm, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C3_1, hang1, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C3_2, hang2, tmotorTetrix, openLoop, reversed)
#pragma config(Servo, srvo_S1_C4_1, flagServo, tServoStandard)
#pragma config(Servo, srvo_S1_C4_2, servo2, tServoNone)
#pragma config(Servo, srvo_S1_C4_3, autoServo, tServoStandard)
#pragma config(Servo, srvo_S1_C4_4, intakeServo, tServoStandard)
#pragma config(Servo, srvo_S1_C4_5, hangServo1, tServoStandard)
#pragma config(Servo, srvo_S1_C4_6, hangServo2, tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard       !!*//


/**********************************
** WHS Robotics  |  FTC Team 542 **
** Block Party! 2013-2014 Season **
** Gamble (Ramp + IR Score)      **
** Main  |  Right  |  V1         **
***********************************/
///////////////////INCLUDES///////////////////
#include "JoystickDriver.c" //driver for receiving bluetooth msgs
#include "arps_functions.h" //header file for ARP Functions


//INITIALIZATION//
//-----------Global Variables
bool needArm = false; //to trigger concurrent movement in the arm, while moving other parts
int crate = 0; //position of IR

//-----------Task to keep servos locked
task LockServos()
{
	while(true)
	{
		resetHang();
		resetFlag();
	}
}

//------------Task to move the arm concurrently
task Arm()
{
	while(true)
	{
		if(needArm)
		{
			moveArm(80);
			wait1Msec(500);
			moveArm(0);
			return;
		}
	}
}

//---------Function for initialization
void initializeRobot()
{
	//ready KONSTANTS
	const int AUTO_INIT = 15;

	//set to ready positions
	servo[autoServo] = AUTO_INIT;

	resetBucket(); //DO NOT reset the NXT motors!!

	//reset drive train encoders
	nMotorEncoder[leftDrive] = 0;
	nMotorEncoder[rightDrive] = 0;

	//lock hang arms
	StartTask(LockServos);
	//start task to lift arm concurrently
	StartTask(Arm);

	//beep to signal end of significance
	PlayTone(440,30);

	return;
}


//MAIN//
task main()
{
	initializeRobot();
	waitForStart();

	//-------------GAMBLE BEGIN----------------
	needArm = true;
	wait1Msec(300);
	//Detect IR beacon
	if(SensorValue[IRSensor] <= 4 && SensorValue[IRSensor] != 0)
	{
		crate = 1;
	}
	else if(SensorValue[IRSensor] == 5)
	{
		crate = 2;
	}
	else if(SensorValue[IRSensor] == 0)//added in SensorValue, it caused everything to go wrong
	{
		crate = 3;
	}
	//---Move forward
	moveStraight(8.0,100.0);
	//---Turn Left
	gyroCenterPivot(-34,100);
	//---Move forward
	moveStraight(27.0,100);
	//---Turn Right
	gyroCenterPivot(93,100);
	//---Get on ramp
	moveStraight(31.0,100);

	//---Check which crate for positioning
	if(crate == 2)
	{
		moveStraight(8.0, 100);
	}
	else if(crate == 3)
	{
		moveStraight(24.0, 100);
	}
	//If crate == 1, then do not move.  Robot is already positioned to score.

	//---Stop
	stopDriveTrain();
	//---SCORE
	scoreAutoArm();
}
