#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          hangmanMot,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          intakeL,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          intakeR,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     sweBL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ttMot,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     sweFL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flagMot,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     sweBR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     armMot,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     sweFR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     winchMot,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S3_C1_1,    swiFR,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    swiBR,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_1,    swiFL,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    swiBL,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    antiRatchet,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S3_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S3_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "auto_globVars_swedr.h"
#include "arps_functions_swedr.h"

task main()
{
	intitializeRobotCarasoul;
	waitForStart();
	raiseArm = true;
	wait1Msec(300);
	if(SensorValue[IRSensor] <= 4 && SensorValue[IRSensor] != 0)
	{
		crate = 1;
	}
	else if(SensorValue[IRSensor] == 5)
	{
		crate = 2;
	}
	else if(SensorValue[IRSensor] == 0)//added in SensorValue, it caused everything to go wrong
	{
		crate = 3;
	}
	moveArm(50);//---Move forward
	//---Move towards the ramp by having servos turn and then moving forward

	if(crate == 2)							//this crate would have to be the closest one to us
	{
		moveStraight(90.0, 30.0, 100);			//motors would be going at 100 power
		gyroCenterPivot(-90, 100);
		dropTheBlock();												//drop the cube into the second crate
		gyroCenterPivot(-90, 100);
		moveStraight(90.0, 30.0, 100);
	}
	else if(crate == 3)
	{
		moveStraight(90.0, 40.0, 100);			//motors would be going at 100 power
		gyroCenterPivot(-90, 100);					//robot will turn 90 degrees to the right
		dropTheBlock();												//drop the cube into the third crate
		gyroCenterPivot(-90, 100);
		moveStraight(90.0, 40.0, 100);
	}
	else
	{
		moveStraight(90.0, 15.0, 100);			//Robot will go forward for 15 inches at 100 power.
		gyroCenterPivot(-90, 100);					//robot will turn 90 degrees to the right
		dropTheBlock();												//drop the cube into the first crate
		gyroCenterPivot(-90, 100);
		moveStraight(90.0, 15.0, 100);
	}
	gyroCenterPivot(45.0, 100);
	moveStraight(90.0, 5.0, 100);
	gyroCenterPivot(90.0, 100);
	moveStraight(90.0, 10.0, 100);
	gyroCenterPivot(45.0, 100);
	moveStraight(90.0, 5.0, 100);
	stopDriveTrain();
//Raise the arm
//Have the servos and towards the crate
//Move forward
//Swivel around
//Drop the cube into the crate
//Then have the servos angled towards the opposite side of the ramp
//Move forward

}
