#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          hangmanMot,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          intakeL,       tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          intakeR,       tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     sweBL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     armL,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     sweFL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     flagMot,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     sweBR,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     armR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     sweFR,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     winchMot,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S3_C1_1,    swiFR,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    swiBR,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    dropbox,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_1,    swiFL,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    swiBL,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    antiRatchet,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S3_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S3_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "arps_functions_swedr.h"
#include "auto_globVars_swedr.h"

int crate = 0;
task main()
{
	waitForStart();
																					//ARM NEEDS TO BE RAISED HIGH ENOUGH THAT IT WILL BE OVER THE CRATES BUT NOT HIT THE BAR
	wait1Msec(300);
	if(SensorValue[IRSensor] <= 4 && SensorValue[IRSensor] != 0)
	{
		crate = 1;
	}
	else if(SensorValue[IRSensor] == 5)
	{
		crate = 2;
	}
	else if(SensorValue[IRSensor] == 0)//added in SensorValue, it caused everything to go wrong
	{
		crate = 3;
	}
	moveStraight(8.0,100.0);
	//---Turn Left
	gyroCenterPivot(-34,100);
	//---Move forward
	moveStraight(27.0,100);
	//---Turn Right
	gyroCenterPivot(93,100);
	//---Get on ramp
	moveStraight(31.0,100);


	if(crate == 2)							//this crate would have to be the closest one to us
	{
		moveStraight(8.0, 100);			//motors would be going at 100 power
		//motor[sweFL] = 100;
		//motor[sweBL] = 100;
		//motor[sweFR] = -100;
		//motor[sweBR] = -100;
		gyroCenterPivot(90.0, 100);
		dropTheBlock();											//drop the cube into the second crate
	}
	else if(crate == 3)
	{
		moveStraight(24.0, 100);			//motors would be going at 100 power
		//motor[sweFL] = 100;
		//motor[sweBL] = 100;
		//motor[sweFR] = -100;
		//motor[sweBR] = -100;				//robot will turn 90 degrees to the right
		gyroCenterPivot(90.0, 100);
		dropTheBlock();											//drop the cube into the third crate
	}
	else
	{
		//motor[sweFL] = 100;
		//motor[sweBL] = 100;
		//motor[sweFR] = -100;
		//motor[sweBR] = -100;
		gyroCenterPivot(90.0, 100);		//robot will turn 90 degrees to the right
		dropTheBlock();												//drop the cube into the first crate
	}
}
