#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     TUX,            sensorHiTechnicTouchMux)
#pragma config(Sensor, S4,     gyroRobot,      sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          flagLeft,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          flagRight,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armRight,      tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     armLeft,       tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************
** WHS Robotics  |  FTC Team 542 **
** Ring It Up! 2012-2013 Season  **
** Autonomous Series 1    			 **
** Offensive direct IR score     **
** Main  |  Blue  |  V1          **
***********************************/


///////////////////////////INCLUDES////////////////////////////
#include "JoystickDriver.c"  //file to "handle" the Bluetooth messages.
#include "autonomous_constants_globVars.h"  //header file with autonomous KONSTANTS and global variables
#include "autonomous_functions1.h"  //header file with autonomous functions
#include "autonomous_tasks1.h"  //header file with autonomous tasks



////////////////////////INITIALIZATION/////////////////////////
void initializeRobot()
{
  resetArm();

	//reset drive train encoders
	nMotorEncoder[driveLeft] = 0;
	nMotorEncoder[driveRight] = 0;

	HTGYROstartCal(gyroRobot); //calibrate gyro

	//clear timers T1 and T2
	ClearTimer(T1);
	ClearTimer(T2);

	resetFlags();

	//beep (because it's Windsor)
	PlayTone(440, 30);

  return;
}



////////////////////////////MAIN///////////////////////////////
task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  //raise arm to IR beacon level
	moveArm(6, 1250);

	//move to plywood
  moveStraight(28,100);

  //Check the IR sensor value
	///IRVal = HTIRS2readACDir(IRSensor);
  IRVal = SensorValue[IRSensor];

  if(IRVal != -1) //IR doesn't return error
	{
	  //----------------IR BEACON IS ON THE RIGHT----------------
		if(IRVal >= 6)
		{
			PlayTone(500, 100); //signal that IR is on right

			///ALIGNING
			//Move back and align to goal

			//back up about one floor tile (24 inches)
			//wait10Msec(50);
			gyroCenterPivot(90,100);
			moveStraight(21, 100); //24
			//moveStraight(9.5/*19*/, -25);

			//turn 45 degrees to line up with beacon
			gyroCenterPivot(-30, 100); //45

			///SCORING
			//Move closer and lift arm
			moveStraight(10, 100);

		  StartTask(ElevatorMusic); //Initiate elevator music

		  //Put ring on peg
			moveArm(20, 1000);
			moveStraight(4, 50); //2.5

			///MOVING BACK
			//Retreat and lower arm
			//lower the arm a bit to back away
			moveArm(-15, 600);
			moveStraight(4, -15);
			moveArm(-13, 600);

			StartTask(Flags); //Triumphantly wave flags

			///DRIVE TO DISPENSER
			moveStraight(3, -15);
			moveStraight(9, -100);
			gyroCenterPivot(-100, 100);
			moveStraight(30, 100);
			//gyroCenterPivot(80, 50);
			//moveStraight(40, 50);

		}
		//----------------IR BEACON IS ON THE LEFT----------------
		else if(IRVal <= 4)
		{
			PlayTone(380, 100); //signal that IR is on left

			///ALIGNING
			//Move back and align to goal

			//move forward more than middle, turn about the same amt.
			gyroCenterPivot(-30, 100);
			moveStraight(28,100);
			gyroCenterPivot(85.5, 100);

			///SCORING
			//Move closer and lift arm
			moveStraight(16, 15);

			StartTask(ElevatorMusic); //Initiate elevator music

			//Put ring on peg
			moveArm(8,1000);
			moveStraight(13, 13);

			///MOVING BACK
			//Retreat and lower arm
			moveArm(-15, 400);
			moveStraight(3, -10);
			moveArm(-20, 430);

			StartTask(Flags); //Triumphantly wave flags

			moveStraight(15, -10);

			///DRIVE TO DISPENSER
			gyroCenterPivot(-100, 50);
			moveStraight(15, 50);
		}
		//----------------IR BEACON IS IN THE MIDDLE----------------
		else if(IRVal == 5)
		{
			PlayTone(440, 100); //signal that IR is in middle

			///ALIGNING
			//Move closer and align to goal
			moveStraight(11, 100); //14
			gyroCenterPivot(49, 100);

			///SCORING
			//Move closer and lift arm
			moveStraight(19, 15);

			StartTask(ElevatorMusic); //Initiate elevator music

			//Put ring on peg
			moveArm(9, 600);
			moveStraight(8.5, 15);

	    ///MOVING BACK
      //Retreat and lower arm
			moveArm(-20, 400);
			moveStraight(3, -10);
			moveArm(-25, 300);
			moveStraight(12, -10);

      StartTask(Flags); //Triumphantly wave flags

      ///DRIVE TO DISPENSER
      gyroCenterPivot(-95, 50);
			moveStraight(30, 50);
		}
	}

  while (true)
  {
  }
}
