#pragma config(Hubs, S1, HTMotor, HTMotor, HTMotor, HTServo)
#pragma config(Sensor, S1, , sensorI2CMuxController)
#pragma config(Sensor, S2, touchSensor, sensorTouch)
#pragma config(Sensor, S3, IRSensor, sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4, gyroSensor, sensorI2CHiTechnicGyro)
#pragma config(Motor, motorA, rightIntake, tmotorNXT, PIDControl, encoder)
#pragma config(Motor, motorB, leftIntake, tmotorNXT, PIDControl, encoder)
#pragma config(Motor, motorC, , tmotorNXT, openLoop)
#pragma config(Motor, mtr_S1_C1_1, leftDrive, tmotorTetrix, PIDControl, reversed)
#pragma config(Motor, mtr_S1_C1_2, rightDrive, tmotorTetrix, PIDControl)
#pragma config(Motor, mtr_S1_C2_1, leftArm, tmotorTetrix, openLoop, reversed)
#pragma config(Motor, mtr_S1_C2_2, rightArm, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C3_1, hang1, tmotorTetrix, openLoop)
#pragma config(Motor, mtr_S1_C3_2, hang2, tmotorTetrix, openLoop, reversed)
#pragma config(Servo, srvo_S1_C4_1, flagServo, tServoStandard)
#pragma config(Servo, srvo_S1_C4_2, servo2, tServoNone)
#pragma config(Servo, srvo_S1_C4_3, autoServo, tServoStandard)
#pragma config(Servo, srvo_S1_C4_4, intakeServo, tServoStandard)
#pragma config(Servo, srvo_S1_C4_5, hangServo1, tServoStandard)
#pragma config(Servo, srvo_S1_C4_6, hangServo2, tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard       !!*//

#include "teleop_tasks2.h";
#include "teleop_globVars1.h";

task main()
{
InitializeRobot();
waitForStart();
StartTask(Intake);
StartTask(Arm);
StartTask(DriveTrain);
//StartTask(Flag);
//ClearTimer(T1);
//wait10Msec(12000);
//StartTask(Hang);
while(true)
{
}
//wait10Msec(3000);
//StopAllTasks();
}
