#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          leftIntake,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightIntake,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftArm,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     hang1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     hang2,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    intakeServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    hangServo1,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    hangServo2,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task DriveTrain()
{
	while(true)
	{
		getJoystickSettings(joystick);
		motor[leftDrive] = abs(joystick.joy1_y1) > 10
		? joystick.joy1_y1
		: 0;
		motor[rightDrive] = abs(joystick.joy1_y2) > 10
		? joystick.joy1_y2
		: 0;
	}
}

task Intake()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy1Btn(4))
		{
			motor[leftIntake] = 100;
			motor[rightIntake] = 100;
		}
		else if(joy1Btn(3))
		{
			servoTarget[intakeServo] = 228;
		}
		else
		{
			servoTarget[intakeServo] = 100;
			motor[rightIntake] = 0;
			motor[leftIntake] = 0;
		}
	}
}

task ScoringArm()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy1Btn(6))
		{
			motor[leftArm] = 80;
			motor[rightArm] = 80;
		}
		else if(joy1Btn(8))
		{
			motor[leftArm] = -60;
			motor[rightArm] = -60;
		}
		else
		{
			motor[leftArm] = 0;
			motor[rightArm] = 0;
		}
	}
}

task Hang()
{
	while(true)
	{
		getJoystickSettings(joystick);
		motor[hang1] = joy1Btn(1)
		?50
		:0;
		motor[hang2] = joy1Btn(1)
		?50
		:0;
		if(joy1Btn(5))
		{
			servoTarget[hangServo1] = 250;
			servoTarget[hangServo2] = 0;
		}
		else if(joy1Btn(7))
		{
			servoTarget[hangServo1] = 90;
			servoTarget[hangServo2] = 160;
		}
		else
		{
		}
	}
}

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		StartTask(DriveTrain);
		StartTask(Intake);
		StartTask(ScoringArm);
		StartTask(Hang);
	}
}
