#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,          rightIntake,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftIntake,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     leftArm,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     hang1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     hang2,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    intakeServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    hangServo1,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    hangServo2,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************
** WHS Robotics  |  FTC Team 542 **
** Block Party! 2013-2014 Season **
** Charge!(Ramp Only)            **
** Main  |  Red  |  V1           **
**********************************/

////////////////////////INCLUDES////////////////////
#include "JoystickDriver.c"; //driver for receiving bluetooth msgs
#include "arps_functions1.h"; //header file for ARP Functions


bool liftArm = false;

//TASKS//
task Arm()
{
	while(true)
	{
		if(arm)
		{
			moveArm(80);
			wait10Msec(50);
			moveArm(0);
			liftArm = false;
			return;
		}
	}
}

//INITIALIZATION//
void initializeRobot()
{
  resetArm();
  resetHang(); //hang arm
  resetBucket(); //DO NOT reset the NXT motors!!

	//reset drive train encoders
	nMotorEncoder[leftDrive] = 0;
	nMotorEncoder[rightDrive] = 0;

	//---------------------------------------------------HTGYROstartCal(gyroRobot); //calibrate gyro

	//clear timers T1 and T2
	ClearTimer(T1);
	ClearTimer(T2);

	//beep to signal end of initialization
	PlayTone(440, 30);

  return;
}



//MAIN//

task main()
{
	int crate = 0;

	//initializeRobot();

	waitForStart();

	StartTask (Arm);
	//----------CHARGE BEGIN------------
	//moveArm(80);
	//---Move forward
	moveStraight(6, 50);
	liftArm = true;
	//---Detect IR Beacon
	//SensorValue[IRSensor];
	//---Turn Right/Left(depending on which side we start)
	gyroCenterPivot(-38,100);
	//---Move forward
	moveStraight(29.0, 50);
	//---Turn Right/Left again
	gyroCenterPivot(93,100);
	//---Get on ramp
	moveStraight(30.0,100);
	//---Move forward if IR Beacon is on the left side
	//if(SensorValue[IRSensor] <= 4 && SensorValue[IRSensor]!=0)
	{
		crate = 1;
		moveStraight(20.0,100);
		gyroCenterPivot(90,50);
		servo[intakeServo] = 150;
		//---Lift Arms

	//---Dump the waffle
	//servo[intakeServo] = 150;
	}/*
	//---Turn Right towards
	//if(SensorValue[IRSensor] == 5)
	{
		crate = 2;
		moveStraight(23.0,100);
		gyroCenterPivot(90,50);
		servo[intakeServo] = 150;
	}
	//if(SensorValue[IRSensor] == 0)
	{
		crate =
		moveStraight(26.0,100);
		gyroCenterPivot(90,50);
		servo[intakeServo] = 150;
	}*/
	//---Stop
	stopDriveTrain();
	//---Park left
	//park(-1);
}
