#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.



void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.


  //nah.
  return;
}

/*The following are random methods that serve
absolutely no purpose at the moment. */
void forward(int power)
{
  motor[motorC] = power;
  motor[motorB] = power;
}


void brake()
{
  motor[motorC] = 0;
  motor[motorB] = 0;
}


void turn(int powerB, int powerC)
{
  motor[motorC] = powerC;
  motor[motorB] = powerB;
}



//The following method, main(), now serves the purpose of the whole program.
task main()
{
  //B is right, C is left
  //initializeRobot(); //it doesn't need initializing cause it's not awesome enough

  //waitForStart();   // wait for start of tele-op phase, but screw that for now

  while (true) //infinite loop
  {
    getJoystickSettings(joystick); //see what the joystick is doing

    int pow_y1 = joystick.joy1_y1/3; //get the y-coordinate of the left joystick
    int pow_y2 = joystick.joy1_y2/3; //get the y-coordinate of the right joystick

    int pow_x1 = joystick.joy1_x1/3; //x-coordinate of left joystick
    int pow_x2 = joystick.joy1_x2/3; //x-coordinate of right joystick

    int b = joystick.joy1_Buttons; //put random button input in this nice variable

    if(abs(pow_x1) < 10 && abs(pow_y1) < 10) //if the left joystick isn't moved
    {
      motor[motorC] = 0; //don't move the motor (duh -_-)
    }
    else //if the left joystick is moved
    {
      if(joy1Btn(5) == 1) //if the 5 button is pressed
      {
        pow_y1 = pow_y1*3; //accelerate motors *3 and move accordingly
        pow_y2 = pow_y2*3;
      }
      //if 5 button is not pressed
      motor[motorA] = pow_y1; //then just move accordingly
      motor[motorC] = pow_y2;
    }
    if(abs(pow_x2) < 10 && abs(pow_y2) < 10) //if the right joystick isn't moved
    {
      motor[motorC] = 0; //THEN DON'T MOVE THE MOTOR. (duh -_-)
    }
    else //if the right joystick is moved
    {
      if(joy1Btn(5) == 1) //if the 5 button is pressed
      {
        pow_y1 = pow_y1*3; //accelerate motors *3 and move accordingly
        pow_y2 = pow_y2*3;
      }
      //if 5 button is not pressed
      motor[motorA] = pow_y1; //then just move accordingly
      motor[motorC] = pow_y2;
    }

    if(joy1Btn(6) == 1) //if the 6 button is pressed
    {
      motor[motorB] = 75; //move attachment motor up
    }
    else if(joy1Btn(8) == 1) //if the 8 button is pressed (assuming the 6 button not pressed)
    {
      motor[motorB] = -75; //move attachment motor up
    }
    else //if the 6 or 8 buttons are not pressed
    {
      motor[motorB] = 0; //don't do anything
    }
  }
}
