#pragma config(StandardModel, "Virtual Worlds NXT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int distance1 = 90;  /*set variable for how far the robot will move*/
int forwardPwr1 = 50; /*set variable for the power at which the motor will move*/

void moveForward(int distance1, int forwardPwr1)
{
  nMotorEncoder[motorB] = 0;  /* Reset motor b*/
  nMotorEncoder[motorC] = 0;  /* Reset motor c*/

  nMotorEncoderTarget[motorB] = distance1;  /*set the motor target to the specified distance*/
  nMotorEncoderTarget[motorC] = distance1;

  motor[motorC] = forwardPwr1;  /*set the power of the motors to the specified power*/
  motor[motorB] = forwardPwr1;

  while(nMotorRunState[motorB] != runStateIdle || nMotorRunState[motorC] != runStateIdle)
    //allow the motors to run until the target is reached and the motors are stationary
  {

  }
}

task main()
{
  moveForward(distance1, forwardPwr1);
}
