#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          leftIntake,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightIntake,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftArm,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     hang1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     hang2,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    intakeServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    hangServo1,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    hangServo2,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Uses Ternary Operators and scaled Joystick Values to output a tank drive
task DriveTrain()
{
	while(true)
	{
		getJoystickSettings(joystick);
		//leftDrive Motor definition
		motor[leftDrive] = abs(joystick.joy1_y1 * 25/32) > 15
		? joystick.joy1_y1 * 25/32 //If greater than threshold output scaled Joystick
		: 0; //Else, 0 power
		//rightDrive Motor definition
		motor[rightDrive] = abs(joystick.joy1_y2 * 25/32) > 15
		? joystick.joy1_y2 * 25/32 //If greater than threshold output scaled Joystick
		: 0; //Else, 0 power
	}
}

//Responsible for Intake Controls (NXT motors and Servo Base Drop)
task Intake()
{
	while(true)
	{
		getJoystickSettings(joystick);
		//Initial condition activates NXT motors for the Intake
		if(joy1Btn(4))
		{
			motor[leftIntake] = 100;
			motor[rightIntake] = 100;
		}
		//Secondary condition activates servo drop
		else if(joy1Btn(3))
		{
			servoTarget[intakeServo] = 228;
			motor[rightIntake] = 0;
			motor[leftIntake] = 0;
		}
		//Disables all motors and returns servo to initial position
		else
		{
			servoTarget[intakeServo] = 75;
			motor[leftIntake] = 100;
			motor[rightIntake] = 100;
		}
	}
}

//Controls Scoring Arm
task ScoringArm()
{
	while(true)
	{
		getJoystickSettings(joystick);
		//Lifts arm
		if(joy1Btn(6))
		{
			motor[leftArm] = 80;
			motor[rightArm] = 80;
		}
		//Lowers Arm
		else if(joy1Btn(8))
		{
			motor[leftArm] = -40;
			motor[rightArm] = -40;
		}
		//Cuts off Power
		else
		{
			motor[leftArm] = 0;
			motor[rightArm] = 0;
		}
	}
}

//Responsible for hang
task Hang()
{
	while(true)
	{
		getJoystickSettings(joystick);
		//Activates winch lift motors
		motor[hang1] = joy1Btn(1)
		?100
		:0;
		motor[hang2] = joy1Btn(1)
		?100
		:0;
		//Only when the button for the lif arms are pressed, lift
		if(joy1Btn(5))
		{
			servoTarget[hangServo1] = 250;
			servoTarget[hangServo2] = 0;
		}
		//Otherwise, Drop the servo arms
		else
		{
			servoTarget[hangServo1] = 90;
			servoTarget[hangServo2] = 160;
		}
	}
}

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		StartTask(DriveTrain);
		StartTask(Intake);
		StartTask(ScoringArm);
		StartTask(Hang);
	}
}
