#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          leftIntake,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightIntake,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     hangMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     tableMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    armServo,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c";
//joystick2 - arm & turntable

//KONSTANTS
final int DRIVE_HI_THRESH = 25;
final int TABLE_HI_POW = 50;
final int TABLE_LOW_POW = 30;
final int INTAKE_POW = 100;
final int STOP = 0;


task DriveTrain() //low priority
{
	while(true)
	{
		getJoystickSettings(joystick);

		//higher thresholds than joy1
		if(abs(joystick.joy2_y1) > DRIVE_HI_THRESH)
		{
			motor[leftDrive] = joystick.joy2_y1;
		}
		else
		{
			motor[leftDrive] = STOP;
		}

		if(abs(joystick.joy2_y2) > DRIVE_HI_THRESH)
		{
			motor[rightDrive] = joystick.joy2_y2;
		}
		else
		{
			motor[rightDrive] = STOP;
		}

	}
}

task Arm() //high priority
{
	while(true)
	{
		getJoystickSettings(joystick);

		if(joy2Btn(6) && !joy2Btn(8)) //raise arm
		{
			//servo[armServo] =
		}
		else
		{
			//code here
		}

		if(joy2Btn(8) && !joy2Btn(6)) //lower arm
		{
			//servo[armServo] =
		}
		else
		{
			//code here
		}

	}
}


task Turntable() //high priority
{
	while(true)
	{
		getJoystickSettings(joystick);

		if(joy2_TopHat == 2 && !(joy2_TopHat == 6)) //turntable right
		{
			if(!joy2Btn(5)) //regular speed
			{
				motor[tableMotor] = TABLE_HI_POW;
			}
			else //slow
			{
				motor[tableMotor] = TABLE_LOW_POW;
			}
		}
		else //if not pressed
		{
			motor[tableMotor] = STOP;
		}

		if(joy2_TopHat == 6 && !(joy2_TopHat == 2)) //turntable left
		{
			if(!joy2Btn(5)) //regular speed
			{
				motor[tableMotor] = -TABLE_HI_POW;
			}
			else //slow
			{
				motor[tableMotor] = -TABLE_LOW_POW;
			}
		}
		else //if not pressed
		{
			motor[tableMotor] = STOP;
		}

	}
}


void runIntake(int power)
{
	motor[leftIntake] = power;
	motor[rightIntake] = power;
}


task Intake() //low priority
{
	while(true)
	{
		getJoystickSettings(joystick);

		if(joy2Btn(2) && !joy2Btn(4)) //eat waffles
		{
			runIntake(INTAKE_POW);
		}
		else
		{
			runIntake(STOP);
		}
		if(joy2Btn(4) && !joy2Btn(2)) //cough waffles
		{
			runIntake(-INTAKE_POW);
		}
		else
		{
			runIntake(STOP);
		}
	}
}

task main()
{


}
