#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    armServo,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task dongers()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if(joy1Btn(2))
		{
			servo[armServo] = 124 + 8;
		}
		if(joy1Btn(4))
		{
			servo[armServo] = 124 - 8;
		}
	}
}

task main()
{
	while(true)
	{
		StartTask(dongers);
	}
}
