#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     excel,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-accelerometer.h";

int excel_x_raw = 0;
int excel_y_raw = 0;
int excel_z_raw = 0;
float excel_x = 0.0;
float excel_y = 0.0;
float excel_z = 0.0;
const float GRAVY = 0.0980665;

task Display()
{
	while(true)
	{
		HTACreadAllAxes(excel,excel_x_raw,excel_y_raw,excel_z_raw);
		excel_x = ((excel_x_raw/100.0)/GRAVY)+2.0;//cm/s^2
		excel_y = (excel_y_raw/100.0)/GRAVY;
		excel_z = (excel_z_raw/100.0)/GRAVY;
		eraseDisplay();
		nxtDisplayString(3,"x: %d", excel_x_raw);
		nxtDisplayString(4,"y: %d", excel_y_raw);
		nxtDisplayString(5,"z: %d", excel_z_raw);
	}
}


task main()
{
	StartTask(Display);
	motor[leftDrive] = 100;
	motor[rightDrive] = 100;
	ClearTimer(T1);
	while(time100[T1] <= 20)
	{/*
		float power = 50.0*sin(time100[T1]/20.0);
		motor[leftDrive] = power;
		motor[rightDrive] = power;*/
	}

	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}
