#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     intakeMot,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "JoystickDriver.c";

bool intakeOn = false;
	string object = "";
	int numBlock = 0;

task Intake()
{
	bool intakeOn = true;
	bool isBlock = false;

	motor[intakeMot] = 60;//50//43//35

	while(numBlock < 4)
	{
		if(SensorValue[lightSensor] > 25) //@p50, 25 //@p43, 25//@p35, 25 //32
		{
			wait1Msec(250);
			if(SensorValue[lightSensor] >= 26) //@p50, 30//@p43, 26 //@p35, 37 //44
			{
				PlayTone(440,1);
				object = "block ";
				isBlock = true;
			}
			else
			{
				PlayTone(300,1);
				object = "paddle";
			}
		}

		else
		{
			object = "      ";
			if(isBlock)
			{
				numBlock++;
				isBlock = false;
			}
		}

			nxtDisplayString(3,"%s",object);
		nxtDisplayString(4,"numBlock: %d", numBlock);
		nxtDisplayString(5,"%d",SensorValue[lightSensor]);
	}
		wait1Msec(1000);//higher angle: higher time
		motor[intakeMot] = 0;
		wait1Msec(1000);
		motor[intakeMot] = -60;
		wait1Msec(1500);
		motor[intakeMot] = 0;


		intakeOn = false;
}

task main()
{
	StartTask(Intake);
	while(true)
	{

	}
	/*while(true)
	{
		getJoystickSettings(joystick);
		if(Joy1Btn(6) && !Joy1Btn(8))
		{
			if(!intakeOn)
			{
				StartTask(Intake);
			}
		}
		else if(Joy1Btn(8) && !Joy1Btn(6))
		{
			motor[intakeMot] = -50;
		}
		else
		{
			motor[intakeMot] = 0;
		}
	}*/
}
