#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     L,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     R,             tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

task main()
{
while(true)
{
	getJoystickSettings(joystick);
	if(joy1Btn(6))
	{
		motor[L] = 100;
		motor[R] = 100;
	}
	else if(joy1Btn(8))
	{
		motor[L] = -100;
		motor[R] = -100;
	}
	else if(joy1Btn(5))
	{
		motor[L] = 50;
		motor[R] = 50;
	}
	else if(joy1Btn(7))
	{
		motor[L] = -50;
		motor[R] = -50;
	}
	else
	{
		motor[L] = 0;
		motor[R] = 0;
	}
}
}
