#pragma config(Motor,  motorA,          ttMot,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//Working copy of turntable tele-op control; just needs scaling

const float ENCODER2TT = 1.0/6.0; //ratio of turntable to motor encoder revolutions
const float JOY2POW = 100.0/128.0; //convert joystick value to motor power
const int JOY_THRESH = 10; //joystick threshold for dead zone

/*
joystick value is proportional to motor power
rotations are limited to [-180,+180]
*/

task main()
{
	nMotorEncoder[ttMot] = 0; //reset motor encoder
	bool posMove = false; //check if positive turn can be made
	bool negMove = false; //check if negative turn can be made

	waitForStart();

	while(true)
	{
		getJoystickSettings(joystick);
		posMove = (joystick.joy1_x1 > JOY_THRESH && nMotorEncoder[ttMot] <= 90*ENCODER2TT);
		negMove = (joystick.joy1_x1 < -JOY_THRESH && nMotorEncoder[ttMot] >= -90*ENCODER2TT);

		if(negMove || posMove) //if significant movement detected and limited by angle
		{
			motor[ttMot] = joystick.joy1_x1*JOY2POW; //set motor power proportional to joystick value
		}
		else //if no significant movement or outside angle limits
		{
			motor[ttMot] = 0; //do not move motor
		}
	}
}
