#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S2,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
#pragma config(Motor,  motorA,          hangmanMot,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          intakeL,       tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          intakeR,       tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     sweBL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     armL,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     sweFL,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     flagMot,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     sweBR,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     armR,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     sweFR,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     winchMot,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S3_C1_1,    swiFR,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    swiBR,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    dropbox,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_1,    swiFL,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    swiBL,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    antiRatchet,          tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S3_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S3_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "arps_functions_swedr.h"

void initializeRobot()
{
	//--wheel positions
	servo[swiFL] = 97;
	servo[swiBL] = 127;
	servo[swiFR] = 127;
	servo[swiBR] = 147;

	//--fastest rates
	muxUpdateInterval = 1;
	servoChangeRate[swiFL] = 0;
	servoChangeRate[swiFR] = 0;
	servoChangeRate[swiBR] = 0;
	servoChangeRate[swiBL] = 0;
	StartTask(HoldBox);//servo[dropbox] = 255;
	StartTask(AntiRat);
	return;
}

task main()
{
	initializeRobot();
	waitForStart();
	//--Get IR reading

	if(SensorValue[IRSensor] == 5)
	{
		//-/writeDebugStreamLine("1,5@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		StartTask(ScoreArm); //--lift arm to score
		moveStraight(37.0,12.0,100.0); //--move towards the crates//moveStraight(65.0,6.0,100.0); dump 25
		if(SensorValue[IRSensor] != 5) //-- if crate 4
		{
			moveStraight(10.0,6.0,-100.0);//moveStraight(40.0,2.0,-50.0);
			//-/writeDebugStreamLine("2,5@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
		}
		//--if crate 3, stay in position
	}
	else //--what the heck, score anyway
	{
		StartTask(ScoreArm); //--lift arm to score
		moveStraight(37.0,12.0,100.0); //--move towards the crates//moveStraight(65.0,6.0,100.0); dump 25
	}

	dropTheBlock();
	while(true){}
}
